name: Compilar Móvil (Android APK)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    # Esto hace que todos los comandos 'run' empiecen ya dentro de esa carpeta
    defaults:
      run:
        working-directory: ./mantenimiento_app

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Instalar Dependencias Flutter
      run: flutter pub get

    - name: Construir APK (Release)
      run: flutter build apk --release --no-tree-shake-icons

    # --- CORRECCIÓN AQUÍ ---
    # Como ya estamos en 'mantenimiento_app', entramos directamente en 'build/...'
    - name: Renombrar APK a MantPro.apk
      run: |
        cd build/app/outputs/flutter-apk/
        mv app-release.apk MantPro.apk

    - name: Subir Artefacto (Siempre)
      uses: actions/upload-artifact@v4
      with:
        name: MantPro-Android-APK
        # Para las acciones 'uses', la ruta SIEMPRE es desde la raíz del repositorio
        path: mantenimiento_app/build/app/outputs/flutter-apk/MantPro.apk

    - name: Publicar en Release (Solo si hay Tag)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # Aquí también ruta completa desde la raíz
        files: mantenimiento_app/build/app/outputs/flutter-apk/MantPro.apk
